name: Deploy to Cloud Run

on:
  push:
    branches:
      - master  # or your branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: web-app-463821
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image and push
        run: |
          gcloud builds submit --tag gcr.io/web-app-463821/web_app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy web-app \
            --image gcr.io/web-app-463821/web_app \
            --region northamerica-northeast2 \
            --platform managed \
            --quiet
